name: backoffice_backend
services:
  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres00

    networks:
      - default

    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    image: byloth/backoffice-backend:latest
    depends_on:
      - postgres

    command: django
    environment:
      PGHOST: postgres
      PGUSER: backoffice
      PGPASSWORD: backoffice00
      SECRET_KEY: yet_not_a_very_secure_secret_key

    networks:
      - default

    ports:
      - 8000:8000

    volumes:
      - django_data:/var/lib/backoffice/backend
      - ./src:/opt/backoffice/backend

networks:
  default:

volumes:
  django_data:
  postgres_data:
